/*
 * This source file was generated by the Gradle 'init' task
 */
package de.nomiskeig.spring2dbml;

class MessageUtils {
    public static String getMessage() {
        return "Hello      World!";
    }
}
