/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation("fr.inria.gforge.spoon:spoon-core:11.0.1-beta-15")
    implementation("jakarta.persistence:jakarta.persistence-api:3.2.0")
}

application {
    // Define the main class for the application.
    mainClass = "de.nomiskeig.spring2dbml.App"
}
tasks.jar {
    manifest.attributes["Main-Class"] = "de.nomiskeig.spring2dbml.App"
    val dependencies = configurations
        .runtimeClasspath
        .get()
        .map(::zipTree) // OR .map { zipTree(it) }
    from(dependencies) {         exclude("META-INF/*.RSA", "META-INF/*.SF", "META-INF/*.DSA")}
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
